export const salonsList = {
    data: [
        {
            id: 'xyz1',
            title: 'Sax & Fon',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz2',
            title: 'Gents Cut',
            avgRating: 5,
            totalRatings: 120,
            address: 'HuberStrasse 10',
            price: 550,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz3',
            title: 'Butcher Place',
            avgRating: 3.2,
            totalRatings: 10,
            address: 'Hufstephon 2',
            price: 300,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz4',
            title: 'Gold lady',
            avgRating: 4,
            totalRatings: 23,
            address: 'Małosadke 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz5',
            title: 'Fin & Fong',
            avgRating: 4,
            totalRatings: 32,
            address: 'Jagermaster 45',
            price: 410,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz6',
            title: 'Silver lady',
            avgRating: 2,
            totalRatings: 4,
            address: 'Savaginon 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz7',
            title: 'Anakin',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 50',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz8',
            title: 'Ms Butterfly',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagsterens 20',
            price: 500,
            currency: 'Kr',
            durationInMinutes: 120,
            timeApt: '12:00'
        },
        {
            id: 'xyz9',
            title: 'Foxy',
            avgRating: 5,
            totalRatings: 4300,
            address: 'Stock 45',
            price: 400,
            currency: 'Kr',
            durationInMinutes: 90,
            timeApt: '12:00'
        },
        {
            id: 'xyz1',
            title: 'Sax & Fon',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz2',
            title: 'Gents Cut',
            avgRating: 5,
            totalRatings: 120,
            address: 'HuberStrasse 10',
            price: 550,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz3',
            title: 'Butcher Place',
            avgRating: 3.2,
            totalRatings: 10,
            address: 'Hufstephon 2',
            price: 300,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz4',
            title: 'Gold lady',
            avgRating: 4,
            totalRatings: 23,
            address: 'Małosadke 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz5',
            title: 'Fin & Fong',
            avgRating: 4,
            totalRatings: 32,
            address: 'Jagermaster 45',
            price: 410,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz6',
            title: 'Silver lady',
            avgRating: 2,
            totalRatings: 4,
            address: 'Savaginon 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz7',
            title: 'Anakin',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 50',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz8',
            title: 'Ms Butterfly',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagsterens 20',
            price: 500,
            currency: 'Kr',
            durationInMinutes: 120,
            timeApt: '12:00'
        },
        {
            id: 'xyz9',
            title: 'Foxy',
            avgRating: 5,
            totalRatings: 4300,
            address: 'Stock 45',
            price: 400,
            currency: 'Kr',
            durationInMinutes: 90,
            timeApt: '12:00'
        },
        {
            id: 'xyz1',
            title: 'Sax & Fon',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz2',
            title: 'Gents Cut',
            avgRating: 5,
            totalRatings: 120,
            address: 'HuberStrasse 10',
            price: 550,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz3',
            title: 'Butcher Place',
            avgRating: 3.2,
            totalRatings: 10,
            address: 'Hufstephon 2',
            price: 300,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz4',
            title: 'Gold lady',
            avgRating: 4,
            totalRatings: 23,
            address: 'Małosadke 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz5',
            title: 'Fin & Fong',
            avgRating: 4,
            totalRatings: 32,
            address: 'Jagermaster 45',
            price: 410,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz6',
            title: 'Silver lady',
            avgRating: 2,
            totalRatings: 4,
            address: 'Savaginon 45',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz7',
            title: 'Anakin',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 50',
            price: 320,
            currency: 'Kr',
            durationInMinutes: 30,
            timeApt: '12:00'
        },
        {
            id: 'xyz8',
            title: 'Ms Butterfly',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagsterens 20',
            price: 500,
            currency: 'Kr',
            durationInMinutes: 120,
            timeApt: '12:00'
        },
        {
            id: 'xyz9',
            title: 'Foxy',
            avgRating: 5,
            totalRatings: 4300,
            address: 'Stock 45',
            price: 400,
            currency: 'Kr',
            durationInMinutes: 90,
            timeApt: '12:00'
        },
    ]
}

export const salons = {
    data: [
        {
            id: 'xyz1',
            imgUrl: 'https://img.beautylaunchpad.com/files/base/allured/all/image/2020/09/16x9/Eartha.5f6265467c0a2.png?auto=format&fit=max&w=1200',
            title: 'Sax & Fon',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 45 1114 Stockholm',
            closingAt: '18:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz2',
            imgUrl: 'https://menhairstylesworld.com/wp-content/uploads/2019/02/pomp-fade-1.jpg',
            title: 'Gents Cut',
            avgRating: 5,
            totalRatings: 120,
            address: 'HuberStrasse 10 124412 Hopasdt',
            closingAt: '18:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz3',
            imgUrl: 'https://menhairstylesworld.com/wp-content/uploads/2019/02/pomp-fade-1.jpg',
            title: 'Butcher Place',
            avgRating: 3.2,
            totalRatings: 10,
            address: 'Hufstephon 2 24412 Hopasd',
            closingAt: '18:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz4',
            imgUrl: 'https://img.beautylaunchpad.com/files/base/allured/all/image/2020/09/16x9/Eartha.5f6265467c0a2.png?auto=format&fit=max&w=1200',
            title: 'Gold lady',
            avgRating: 4,
            totalRatings: 23,
            address: 'Małosadke 45 53523 Tokyo',
            closingAt: '18:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz5',
            imgUrl: 'https://menhairstylesworld.com/wp-content/uploads/2019/02/pomp-fade-1.jpg',
            title: 'Fin & Fong',
            avgRating: 4,
            totalRatings: 32,
            address: 'Jagermaster 45 123 Stockholm',
            closingAt: '18:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz6',
            imgUrl: 'https://img.beautylaunchpad.com/files/base/allured/all/image/2020/09/16x9/Eartha.5f6265467c0a2.png?auto=format&fit=max&w=1200',
            title: 'Silver lady',
            avgRating: 2,
            totalRatings: 4,
            address: 'Savaginon 45 1112 Athens',
            closingAt: '18:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz7',
            imgUrl: 'https://menhairstylesworld.com/wp-content/uploads/2019/02/pomp-fade-1.jpg',
            title: 'Anakin',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagster 50 9999 Stockholm',
            closingAt: '20:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz8',
            imgUrl: 'https://img.beautylaunchpad.com/files/base/allured/all/image/2020/09/16x9/Eartha.5f6265467c0a2.png?auto=format&fit=max&w=1200',
            title: 'Ms Butterfly',
            avgRating: 4,
            totalRatings: 32,
            address: 'Radmagsterens 20 0009 WomberLand',
            closingAt: '20:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
        {
            id: 'xyz9',
            imgUrl: 'https://img.beautylaunchpad.com/files/base/allured/all/image/2020/09/16x9/Eartha.5f6265467c0a2.png?auto=format&fit=max&w=1200',
            title: 'Foxy',
            avgRating: 5,
            totalRatings: 4300,
            address: 'Stock 45 2929 Stockholm',
            closingAt: '20:00',
            phone: '111-222-333',
            website: 'www.google.com',
            bodyContent: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        },
    ]
}